### ISSUE TITLE
Use correct term for ssh

### ISSUE THREAD

**Issue by ismay** [ismay/dotfiles#20]
`clear` doesn't work with xterm italic

**Comment by dkarter** [comment]
I've been having many issues for ssh with this TERM setup. 
Backspace is not working and tmux on the remote machine does not have colors enabled. Is there a way to set TERM differently for ssh connections? @ismay

**Comment by dkarter** [comment]
I did some googling and found this 

```sh
alias ssh="TERM=xterm-256color ssh"
```

https://gist.github.com/sos4nt/3187620

Seems to work great.

**Comment by ismay** [comment]
@dkarter Ah that's great! Works like a charm, thanks!
