### ISSUE TITLE
Missing Powerline Symbols

### ISSUE THREAD

**Issue by derBingle** [ismay/dotfiles#55]
First, thanks for the amazing dotfiles. Ended up here from unixporn, FYI...

I've tried a couple different Powerline fonts (Source Code, Roboto), and still no luck getting the symbols to show up correctly, as you can see in the screenshot.

Have tried both iTerm's non-ASCII font and switching the main font to a Powerline-compatible one. No dice either way.

Would appreciate if you had any ideas!
<img width="1440" alt="screen shot 2017-03-14 at 2 26 41 am" src="https://cloud.githubusercontent.com/assets/22374934/23890166/857ca2a2-085e-11e7-88d1-fe9a57ecff99.png">

**Comment by ismay** [comment]
Yeah for that you need a so-called nerdfont (powerline patched fonts don't include the icons). You can find those here: https://github.com/ryanoasis/nerd-fonts

That should do the trick!

**Comment by derBingle** [comment]
Thanks so much for the quick fix @ismay! 

I've got a gorgeous, functional, and backed up command line on my new MBP thanks in large part to this repo! :fire: :bowtie:

Many thanks!

**Comment by ismay** [comment]
Anytime, happy to help! 👍
